# Generated by Django 3.1.4 on 2021-08-24 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('guid', models.CharField(blank=True, max_length=50, verbose_name='全局唯一标识')),
                ('name', models.CharField(max_length=200, verbose_name='视频名称')),
                ('desc', models.CharField(blank=True, max_length=500, verbose_name='视频描述')),
                ('artists', models.CharField(default='', max_length=200, verbose_name='演员')),
                ('release_time', models.DateTimeField(null=True, verbose_name='上映时间')),
                ('m3u8_url', models.CharField(max_length=300, verbose_name='视频地址')),
                ('thumb_url', models.CharField(max_length=300, verbose_name='缩略图')),
                ('sort', models.IntegerField(default=100, verbose_name='排序前后')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否启用')),
                ('create_id', models.IntegerField(verbose_name='创建人ID')),
                ('create_name', models.CharField(max_length=10, verbose_name='创建人姓名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_id', models.IntegerField(verbose_name='更新人ID')),
                ('update_name', models.CharField(max_length=10, verbose_name='更新人姓名')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否已删除')),
            ],
            options={
                'verbose_name': '视频表单',
                'verbose_name_plural': '视频表单',
                'db_table': 'tb_base_video',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('desc', models.CharField(blank=True, max_length=300, null=True, verbose_name='分类描述')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否启用')),
                ('sort', models.IntegerField(default=100, verbose_name='排序前后')),
                ('create_id', models.IntegerField(verbose_name='创建人ID')),
                ('create_name', models.CharField(max_length=10, verbose_name='创建姓名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updater_name', models.CharField(max_length=10, verbose_name='更新人姓名')),
                ('updater_id', models.IntegerField(verbose_name='更新人ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否已删除')),
            ],
            options={
                'verbose_name': '分类表',
                'verbose_name_plural': '分类表',
                'db_table': 'tb_category',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('module', models.CharField(max_length=80, verbose_name='所属模块')),
                ('name', models.CharField(max_length=80, verbose_name='变量名称')),
                ('desc', models.CharField(max_length=80, verbose_name='变量描述')),
                ('codename', models.CharField(max_length=40, verbose_name='key')),
                ('value', models.CharField(max_length=255, verbose_name='变量value')),
                ('create_id', models.IntegerField(verbose_name='创建人ID')),
                ('create_name', models.CharField(max_length=10, verbose_name='创建姓名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updater_name', models.CharField(max_length=10, verbose_name='更新人姓名')),
                ('updater_id', models.IntegerField(verbose_name='更新人ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否已删除')),
            ],
            options={
                'verbose_name': '网站配置表',
                'verbose_name_plural': '网站配置表',
                'db_table': 'tb_config',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
                ('desc', models.CharField(blank=True, max_length=300, null=True, verbose_name='标签描述')),
                ('sort', models.IntegerField(default=100, verbose_name='排序前后')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否启用')),
                ('create_id', models.IntegerField(verbose_name='创建人ID')),
                ('create_name', models.CharField(max_length=10, verbose_name='创建姓名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updater_name', models.CharField(max_length=10, verbose_name='更新人姓名')),
                ('updater_id', models.IntegerField(verbose_name='更新人ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否已删除')),
            ],
            options={
                'verbose_name': '标签表',
                'verbose_name_plural': '标签表',
                'db_table': 'tb_tags',
            },
        ),
        migrations.CreateModel(
            name='UserTravel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('operation', models.CharField(choices=[('come', '进入'), ('leave', '离开'), ('favor', '喜爱'), ('oppose', '抵触'), ('comment', '评论'), ('share', '分享'), ('reward', '打赏'), ('spend', '花钱')], max_length=20, verbose_name='操作类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='视频')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.basevideo', verbose_name='视频')),
            ],
            options={
                'verbose_name': '用户轨迹表',
                'verbose_name_plural': '用户轨迹表',
                'db_table': 'tb_user_travel',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('content', models.CharField(max_length=500, verbose_name='评论内容')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='评分')),
                ('favor_count', models.IntegerField(default=0, verbose_name='赞成数')),
                ('oppose_count', models.IntegerField(default=0, verbose_name='反对数')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否启用')),
                ('create_id', models.IntegerField(verbose_name='创建人ID')),
                ('create_name', models.CharField(max_length=10, verbose_name='创建姓名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.basevideo', verbose_name='视频')),
            ],
            options={
                'verbose_name': '评论表',
                'verbose_name_plural': '评论表',
                'db_table': 'tb_comment',
            },
        ),
        migrations.AddField(
            model_name='basevideo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.category', verbose_name='视频类别'),
        ),
        migrations.AddField(
            model_name='basevideo',
            name='tags',
            field=models.ManyToManyField(to='core.Tags', verbose_name='视频标签'),
        ),
    ]
