# Generated by Django 3.1.4 on 2021-08-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deeds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('title', models.CharField(max_length=80, verbose_name='活动标题')),
                ('content', models.TextField(blank=True, default=[], verbose_name='活动内容')),
                ('create_id', models.IntegerField(verbose_name='创建人ID')),
                ('create_name', models.CharField(max_length=10, verbose_name='创建姓名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updater_id', models.IntegerField(verbose_name='更新人ID')),
                ('updater_name', models.CharField(max_length=10, verbose_name='更新人姓名')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '活动表',
                'verbose_name_plural': '活动表',
                'db_table': 'tb_deeds',
            },
        ),
        migrations.RenameField(
            model_name='basevideo',
            old_name='update_id',
            new_name='updater_id',
        ),
        migrations.RenameField(
            model_name='basevideo',
            old_name='update_name',
            new_name='updater_name',
        ),
    ]
