# Generated by Django 3.1.4 on 2021-08-31 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210826_1303'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Discover',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
        #         ('name', models.CharField(max_length=50, verbose_name='名称')),
        #         ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
        #         ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
        #         ('sort', models.IntegerField(default=100, verbose_name='排序前后')),
        #         ('create_id', models.IntegerField(verbose_name='创建人ID')),
        #         ('create_name', models.CharField(max_length=10, verbose_name='创建姓名')),
        #         ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        #         ('updater_name', models.CharField(max_length=10, verbose_name='更新人姓名')),
        #         ('updater_id', models.IntegerField(verbose_name='更新人ID')),
        #         ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
        #         ('is_delete', models.BooleanField(default=False, verbose_name='是否已删除')),
        #     ],
        #     options={
        #         'verbose_name': '发现表',
        #         'verbose_name_plural': '发现表',
        #         'db_table': 'tb_discover',
        #     },
        # ),
        migrations.AlterField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.basevideo', verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='usertravel',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.basevideo', verbose_name='视频'),
        ),
        # migrations.AddField(
        #     model_name='comment',
        #     name='discover',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.discover', verbose_name='发现'),
        # ),
        # migrations.AddField(
        #     model_name='usertravel',
        #     name='discover',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.discover', verbose_name='发现'),
        # ),
    ]
