# Generated by Django 3.1.4 on 2021-09-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210903_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basevideo',
            name='create_name',
            field=models.CharField(max_length=40, verbose_name='创建人姓名'),
        ),
        migrations.AlterField(
            model_name='basevideo',
            name='updater_name',
            field=models.CharField(max_length=40, verbose_name='更新人姓名'),
        ),
        migrations.AlterField(
            model_name='category',
            name='create_name',
            field=models.CharField(max_length=40, verbose_name='创建姓名'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updater_name',
            field=models.CharField(max_length=40, verbose_name='更新人姓名'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_name',
            field=models.CharField(max_length=40, verbose_name='创建姓名'),
        ),
        migrations.AlterField(
            model_name='config',
            name='create_name',
            field=models.CharField(max_length=40, verbose_name='创建姓名'),
        ),
        migrations.AlterField(
            model_name='config',
            name='updater_name',
            field=models.CharField(max_length=40, verbose_name='更新人姓名'),
        ),
        migrations.AlterField(
            model_name='deeds',
            name='create_name',
            field=models.CharField(max_length=40, verbose_name='创建姓名'),
        ),
        migrations.AlterField(
            model_name='deeds',
            name='updater_name',
            field=models.CharField(max_length=40, verbose_name='更新人姓名'),
        ),
        migrations.AlterField(
            model_name='discover',
            name='create_name',
            field=models.CharField(max_length=40, verbose_name='创建姓名'),
        ),
        migrations.AlterField(
            model_name='discover',
            name='updater_name',
            field=models.CharField(max_length=40, verbose_name='更新人姓名'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='create_name',
            field=models.CharField(max_length=40, verbose_name='创建姓名'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='updater_name',
            field=models.CharField(max_length=40, verbose_name='更新人姓名'),
        ),
    ]
