# Generated by Django 3.1.7 on 2022-01-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_groupmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='collapse',
            field=models.BooleanField(default=0, verbose_name='是否折叠'),
        ),
    ]
