# Generated by Django 3.1.7 on 2022-01-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_groupmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=160, verbose_name='菜单URL'),
        ),
    ]
