# Generated by Django 3.1.7 on 2022-01-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220115_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='require_Login',
            field=models.BooleanField(default=0, verbose_name='是否需要登录才能访问'),
        ),
    ]
