# Generated by Django 3.1.7 on 2022-01-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_menu_collapse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='collapse',
        ),
    ]
