# Generated by Django 3.1.7 on 2022-01-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220115_2103'),
        ('core', '0010_remove_menu_collapse'),
    ]

    operations = [
    ]
