# Generated by Django 3.1.7 on 2022-01-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20220117_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('name', models.CharField(max_length=50, verbose_name='地区名称')),
                ('sort', models.IntegerField(default=100, verbose_name='排序前后')),
            ],
            options={
                'verbose_name': '地区表',
                'verbose_name_plural': '地区表',
                'db_table': 'tb_area',
            },
        ),
    ]
