# Generated by Django 3.1.7 on 2022-01-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='require_login',
        ),
        migrations.AddField(
            model_name='menu',
            name='is_nav',
            field=models.BooleanField(default=1, verbose_name='是否为导航'),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_show',
            field=models.BooleanField(default=1, verbose_name='是否展示'),
        ),
    ]
